PLAYERS = [
    {"name": "Lucas",     "play": "Medium",      "run": "Medium",      "goals": "Medium",      "team": 0, "playing": 1},
    {"name": "Gonza",     "play": "Low",         "run": "Medium",      "goals": "Low",         "team": 0, "playing": 0},
    {"name": "Bruno",     "play": "Medium Low",  "run": "Medium",      "goals": "Medium High", "team": 0, "playing": 0},
    {"name": "Tucu",      "play": "Medium",      "run": "Medium Low",  "goals": "Medium Low",  "team": 0, "playing": 0},
    {"name": "Joaco",     "play": "Medium",      "run": "Medium Low",  "goals": "Low",         "team": 0, "playing": 0},
    {"name": "Guille",    "play": "Medium Low",  "run": "Medium Low",  "goals": "Low",         "team": 0, "playing": 0},
    {"name": "Mati",      "play": "Medium High", "run": "High",        "goals": "Medium High", "team": 0, "playing": 1},
    {"name": "Chapa",     "play": "Low",         "run": "Low",         "goals": "Medium Low",  "team": 0, "playing": 0},
    {"name": "Panchi",    "play": "High",        "run": "High",        "goals": "High",        "team": 0, "playing": 0},
    {"name": "Manu",      "play": "Medium",      "run": "High",        "goals": "Medium",      "team": 0, "playing": 1},
    {"name": "Jujeno",    "play": "Medium",      "run": "High",        "goals": "Medium Low",  "team": 0, "playing": 1},
    {"name": "Migue",     "play": "High",        "run": "High",        "goals": "Medium",      "team": 0, "playing": 0},
    {"name": "Chino",     "play": "Medium High", "run": "High",        "goals": "Medium High", "team": 0, "playing": 0},
    {"name": "Negro",     "play": "High",        "run": "High",        "goals": "Medium",      "team": 0, "playing": 0},
    {"name": "Justo",     "play": "Medium",      "run": "High",        "goals": "High",        "team": 0, "playing": 1},
    {"name": "Mitza",     "play": "Medium",      "run": "Medium Low",  "goals": "Medium High", "team": 0, "playing": 1},
    {"name": "Falso",     "play": "Low",         "run": "Low",         "goals": "Low",         "team": 0, "playing": 0},
    {"name": "Facu",      "play": "Medium High", "run": "High",        "goals": "Medium Low",  "team": 0, "playing": 1},
    {"name": "Guido",     "play": "High",        "run": "High",        "goals": "High",        "team": 0, "playing": 0},
    {"name": "Quatz",     "play": "Medium",      "run": "Medium Low",  "goals": "Medium Low",  "team": 0, "playing": 0},
    {"name": "Juani",     "play": "Medium",      "run": "Medium High", "goals": "Medium",      "team": 0, "playing": 1},
    {"name": "Fran",      "play": "High",        "run": "High",        "goals": "High",        "team": 0, "playing": 1},
    {"name": "Marian",    "play": "Medium Low",  "run": "High",        "goals": "Low",         "team": 0, "playing": 0},
    {"name": "Mufas",     "play": "Medium Low",  "run": "Medium Low",  "goals": "Low",         "team": 0, "playing": 0},
    {"name": "Benja",     "play": "Medium",      "run": "Medium High", "goals": "Medium High", "team": 0, "playing": 1},
    {"name": "Tincho",    "play": "High",        "run": "Medium High", "goals": "High",        "team": 0, "playing": 1},
    {"name": "Luqui Bal", "play": "Medium Low",  "run": "Medium Low",  "goals": "Medium Low",  "team": 0, "playing": 0},
    {"name": "Pepetche",  "play": "Medium",      "run": "Medium",      "goals": "Medium",      "team": 0, "playing": 1},
]
